version: "3.1"

services:

  web:
    build: ./meditations
    depends_on:
      - db
    environment:
      - FLASK_APP: meditations
      - FLASK_ENV: development
    ports:
      - "5000:5000"
    volumes:
      - ./meditations:/home/app

  db:
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD: ${PG_PASSWORD}
      - POSTGRES_USER: root
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:

  pgdata:
