version: "3.1"

services:
  web:
    build: ./meditations
    depends_on:
      - db
    env_file:
      - dev.env
    ports:
      - "5000:5000"
    volumes:
      - ./meditations:/home/app/meditations
  db:
    image: postgres:13-alpine
    restart: always
    env_file:
      - dev.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

